import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Sidebar } from "./components/Sidebar";
import { TrialGuard } from "./components/TrialGuard";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TrialGuard>
          <div className="flex min-h-screen bg-slate-100">
            <div className="sticky top-0 h-screen">
              <Sidebar />
            </div>
            <main className="flex-1 p-8 overflow-y-auto">{children}</main>
          </div>
        </TrialGuard>
      </body>
    </html>
  );
}
